/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author SVE14132CW
 */
public class TiketViewPembelian extends javax.swing.JFrame {

    /**
     * Creates new form ViewPembelianTiket
     */
    public TiketViewPembelian() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        NamaKaryawan2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tfNamaPelanggan2 = new javax.swing.JTextField();
        tfUmur2 = new javax.swing.JTextField();
        tfTanggal2 = new javax.swing.JTextField();
        tfIDPenerbangan2 = new javax.swing.JTextField();
        tfJumlahTiket2 = new javax.swing.JTextField();
        tfKTP2 = new javax.swing.JTextField();
        tbMenu2 = new javax.swing.JButton();
        tbBatal2 = new javax.swing.JButton();
        tfJK = new javax.swing.JTextField();
        tbLanjut = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        tfIDPelanggan = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tfTotalHarga = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        NamaKaryawan2.setText("Nama Karyawan");

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel17.setText("Pembelian Tiket");

        jLabel18.setText("Nama");

        jLabel19.setText("No KTP");

        jLabel20.setText("Umur");

        jLabel21.setText("Jenis Kelamin");

        jLabel22.setText("Tanggal");

        jLabel23.setText("Id Penerbangan");

        jLabel24.setText("Jumlah Tiket");

        tfNamaPelanggan2.setEditable(false);
        tfNamaPelanggan2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNamaPelanggan2.setText("Nama");

        tfUmur2.setEditable(false);
        tfUmur2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfUmur2.setText("Umur");

        tfTanggal2.setEditable(false);
        tfTanggal2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTanggal2.setText("Tanggal Penerbangan");

        tfIDPenerbangan2.setEditable(false);
        tfIDPenerbangan2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfIDPenerbangan2.setText("ID Penerbangan");

        tfJumlahTiket2.setEditable(false);
        tfJumlahTiket2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfJumlahTiket2.setText("Jumlah Tiket");

        tfKTP2.setEditable(false);
        tfKTP2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfKTP2.setText("No Ktp");

        tbMenu2.setText("Menu");

        tbBatal2.setText("Batal");
        tbBatal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbBatal2ActionPerformed(evt);
            }
        });

        tfJK.setEditable(false);
        tfJK.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfJK.setText("Jenis Kelamin");

        tbLanjut.setText("Lanjut");
        tbLanjut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbLanjutActionPerformed(evt);
            }
        });

        jLabel25.setText("ID Pelanggan");

        tfIDPelanggan.setEditable(false);
        tfIDPelanggan.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfIDPelanggan.setText("ID Pelanggan");

        jLabel26.setText("Total");

        tfTotalHarga.setEditable(false);
        tfTotalHarga.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfTotalHarga.setText("Total Harga");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(120, 120, 120)
                .addComponent(NamaKaryawan2))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tbMenu2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel26))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfJumlahTiket2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfJK, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfUmur2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfKTP2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfIDPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfNamaPelanggan2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfIDPenerbangan2, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(tbBatal2)
                                .addGap(19, 19, 19)
                                .addComponent(tbLanjut)))))
                .addGap(0, 51, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NamaKaryawan2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel17)))
                .addGap(30, 30, 30)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tfIDPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel18))
                    .addComponent(tfNamaPelanggan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(tfKTP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfUmur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))))
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tfJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTanggal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfIDPenerbangan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfJumlahTiket2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tbBatal2)
                    .addComponent(tbLanjut))
                .addGap(24, 24, 24)
                .addComponent(tbMenu2)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbBatal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbBatal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbBatal2ActionPerformed

    private void tbLanjutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbLanjutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbLanjutActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel NamaKaryawan2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton tbBatal2;
    private javax.swing.JButton tbLanjut;
    private javax.swing.JButton tbMenu2;
    private javax.swing.JTextField tfIDPelanggan;
    private javax.swing.JTextField tfIDPenerbangan2;
    private javax.swing.JTextField tfJK;
    private javax.swing.JTextField tfJumlahTiket2;
    private javax.swing.JTextField tfKTP2;
    private javax.swing.JTextField tfNamaPelanggan2;
    private javax.swing.JTextField tfTanggal2;
    private javax.swing.JTextField tfTotalHarga;
    private javax.swing.JTextField tfUmur2;
    // End of variables declaration//GEN-END:variables

    public JButton getTbBatal2() {
        return tbBatal2;
    }

    public JButton getTbLanjut() {
        return tbLanjut;
    }

    public JButton getTbMenu2() {
        return tbMenu2;
    }

    public JTextField getTfIDPelanggan() {
        return tfIDPelanggan;
    }

    public JTextField getTfIDPenerbangan2() {
        return tfIDPenerbangan2;
    }

    public JTextField getTfJK() {
        return tfJK;
    }

    public JTextField getTfJumlahTiket2() {
        return tfJumlahTiket2;
    }

    public JTextField getTfKTP2() {
        return tfKTP2;
    }

    public JTextField getTfNamaPelanggan2() {
        return tfNamaPelanggan2;
    }

    public JTextField getTfTanggal2() {
        return tfTanggal2;
    }

    public JTextField getTfTotalHarga() {
        return tfTotalHarga;
    }

    public JTextField getTfUmur2() {
        return tfUmur2;
    }

    public void setActionListener(ActionListener ae) {
        tbBatal2.addActionListener(ae);
        tbLanjut.addActionListener(ae);
        tbMenu2.addActionListener(ae);
        tfIDPelanggan.addActionListener(ae);
        tfIDPenerbangan2.addActionListener(ae);
        tfJK.addActionListener(ae);
        tfJumlahTiket2.addActionListener(ae);
        tfKTP2.addActionListener(ae);
        tfNamaPelanggan2.addActionListener(ae);
        tfTotalHarga.addActionListener(ae);
        tfUmur2.addActionListener(ae);
    }
}
